spring:
  application:
    name: "workshop3"
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: "mongodb+srv://user_admin:Gc5PmFZ5PabWMZEf@cluster0.yrntkij.mongodb.net/jwt_reactive_security?retryWrites=true&w=majority"